# .readthedocs.yml

version: 1

build:
  os: ubuntu-20.04

  tools:
    python: "3.8"

build:
  image: latest
  # image: stable

python:
  version: 3.8

python:
  install:
    - requirements: docs/requirements.txt
    - requirements: requirements.txt

sphinx:
   configuration: docs/conf.py
  #  fail_on_warning: true