# .readthedocs.yml

version: 2

build:
  # image: latest
  # image: stable
  os: ubuntu-22.04
  tools:
    python: "3.8"

python:
  version: 3.8

python:
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt

sphinx:
   configuration: docs/conf.py
  #  fail_on_warning: true

# formats: all