name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Tests
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - uses: actions/setup-python@v4
      with:
        python-version: '3.7.6'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    
    - name: Check formatting with black
      run: |
        black --check py_ephys tests
    
    - name: Check imports with isort
      run: |
        isort -c py_ephys tests

    - name: Check types with pyright
      run: |
        pyright py_ephys

    - name: Test with pytest
      run: |
        pip install pytest
        pytest tests/
